version: '2'

services:

    cardano-node:
        image: ststolz/cardano-node:latest
        container_name: stolz-cardano-relay
        network_mode: host
        volumes:
            #- ./files:/opt/cardano/cnode/files
            - ./db:/opt/cardano/cnode/db
            - ./sockets:/opt/cardano/cnode/sockets
            - ./priv:/opt/cardano/cnode/priv
            - ./tmp:/tmp
        build:
            dockerfile: Dockerfile
            context: ./

        command: [ 
        #            "--port", "7030",
        #            "--host-addr <PUBLIC IP>",
        #            "--shelley-kes-key kes.skey",
        #            "--shelley-vrf-key vrf.skey",
        #            "--shelley-operational-certificate node.cert" 
        ]