version: '2'

services:

    cardano-node:
        image: ststolz/cardano-node:latest
        container_name: stolz-cardano-relay
        network_mode: host
        volumes:
            #- ./files:/files
            - ./db:/opt/cardano/cnode/db
            - ./sockets:/opt/cardano/cnode/sockets
            #- ./scripts:/scripts
        build:
            dockerfile: Dockerfile
            context: ./
        command: ["cardano-node", "run", 
                    "--config", "/opt/cardano/cnode/files/mainnet-config.json", 
                    "--topology", "/opt/cardano/cnode/files/mainnet-topology.json", 
                    "--database-path", "/db", 
                    "--socket-path", "/opt/cardano/cnode/sockets/node0.socket",
                    "--port", "7030"
                    ]
        