version: '2'

services:

    cardano-testnet-node:
        image: ststolz/cardano-node:1.23.0-testnet
        container_name: stolz-cardano-testnet-relay
        network_mode: host
        volumes:
            #- ./files:/opt/cardano/cnode/files
            - ./db-testnet:/opt/cardano/cnode/db
            - ./sockets:/opt/cardano/cnode/sockets
            - ./priv-testnet:/opt/cardano/cnode/priv
            - ./tmp:/tmp
        build:
            dockerfile: Dockerfile
            context: ./
            args:
                net: testnet
        #command: [ 
        #            "--host-addr <PUBLIC IP>",
        #            "--shelley-kes-key kes.skey",
        #            "--shelley-vrf-key vrf.skey",
        #            "--shelley-operational-certificate node.cert" 
        #          ]
        