version: '2'

services:

    cardano-node:
        image: ststolz/cardano-node:latest
        container_name: stolz-cardano-relay
        network_mode: host
        volumes:
            - ./config:/configuration
            - ./data:/data
            - ./ipc:/ipc
        build:
            dockerfile: Dockerfile
            context: ./
        command: ["cardano-node", "run", 
                    "--config", "/configuration/testnet-config.json", 
                    "--topology", "/configuration/testnet-topology.json", 
                    "--database-path", "/data/db", 
                    "--port", "7030", 
                    "--host-addr", "x.x.x.x", 
                    "--socket-path", "/ipc/node.socket"]
        