version: '2'

services:

    cardano-node:
        image: ststolz/cardano-node:latest
        container_name: stolz-cardano-testnet-relay
        network_mode: host
        volumes:
            #- ./files:/files-testnet
            - ./db-testnet:/opt/cardano/cnode/db-testnet
            - ./sockets:/opt/cardano/cnode/sockets
            #- ./scripts:/scripts
        build:
            dockerfile: Dockerfile
            context: ./
        command: ["cardano-node", "run", 
                    "--config", "/opt/cardano/cnode/files-testnet/testnet-config.json", 
                    "--topology", "/opt/cardano/cnode/files-testnet/testnet-topology.json", 
                    "--database-path", "/db-testnet", 
                    "--socket-path", "/opt/cardano/cnode/sockets/node0.socket",
                    "--port", "7031"
                    ]
        