name: Publish Docker image
on:
 push:
   tags:
     - "*"
jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:     

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ststolz/cardano-node
          #tag_with_ref: true
          auto_tag: true
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})      
      - name: Build the tagged Docker image for testnet
        run: docker build --build-arg net=testnet . --file Dockerfile --tag ststolz/cardano-node:${{steps.vars.outputs.tag}}-testnet
      - name: Push the tagged Docker image
        run: docker push ststolz/cardano-node:${{steps.vars.outputs.tag}}-testnet
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag ststolz/cardano-node:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push ststolz/cardano-node:${{steps.vars.outputs.tag}}

      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     push: true
      #     tags: ststolz/cardano-node:latest
      #     build-args: |
      #       arg1=value1
      #       arg2=value2

      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}